### ISSUE TITLE
getorderbook throws error in empty markets

### ISSUE THREAD

**Issue by madsurgeon** [ropensci/bittrex#13]
Hi,
getorderbook throws an error when a market is empty, right now for example
`> getorderbook("BTC-XVC")`
`Error in names(buy) <- tolower(names(buy)) : 
  attempt to set an attribute on NULL`

As the coin is still listed in other API results, this case should be taken care of.

**Comment by kaneplusplus** [comment]
Thanks for pointing this out. I've made changes to detect and return an empty data frame. This was done in favor of checking to see if the market is available since that would cost an API call on a rate limited API server. In practice, you might want to get all of the markets and see if your market of interest (in this case ("BTC-XVC")) is included.

The changes are included in 0.1.9, which has been checked in and is building.
